version: '3.5'

services:
  allure:
    container_name: allure
    hostname: allure
    build:
      context: ./allure-docker-service
      dockerfile: docker-custom/Dockerfile.bionic-custom
      args:
        ALLURE_RELEASE: "2.13.5"
    environment:
      DEV_MODE: 0
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 5
      #URL_PREFIX: "/my-prefix"
      SECURITY_USER: "david"
      SECURITY_PASS: "!QAZ2wsx#EDC"
      SECURITY_ENABLED: 1
      #ACCESS_TOKEN_EXPIRES_IN_SECONDS: 10
      #REFRESH_TOKEN_EXPIRES_IN_SECONDS: 10
      #
    ports:
      - "${ALLURE_API_PORT}:5050"
    volumes:
      #- ${PWD}/results:/app/allure-results
      #- ${PWD}/reports:/app/default-reports
      - ${PWD}/projects:/app/projects
    restart: always
    networks:
      - monitor

  allure-ui:
    container_name: allure-ui
    hostname: allure-ui 
    build:
      context: ./allure-docker-service-ui
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "na"
        VERSION: "na"
        VCS_REF: "na"
    environment:
      #ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      #ALLURE_DOCKER_PUBLIC_API_URL: "http://allure:${ALLURE_API_PORT}"
      ALLURE_DOCKER_PUBLIC_API_URL: "http://192.168.100.190:${ALLURE_API_PORT}"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
      #URL_PREFIX: "/my-prefix"
    ports:
      - "5252:5252"
    restart: always
    networks:
      - monitor

networks:
  monitor:
    name: monitor


